apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: k3k-test
  namespace: kraft
spec:
  rules:
  - host: kraft.alexbissessur.dev
    http:
      paths:
      - backend:
          service:
            name: kraft-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
